### ISSUE TITLE
PHP Strict standards:  Declaration of StripeSlackPage_Controller::success() should be compatible with Page_Controller::success(SS_HTTPRequest $r)

### ISSUE THREAD

**Issue by robbieaverill** [Firesphere/silverstripe-stripeslack#12]
I realise that Page_Controller doesn't have success() defined by default, but if it is then it will at least have a request parameter. Could we add the param to StripeSlackPage_Controller? It will be B/C

**Comment by Firesphere** [comment]
Please see issue #13 , I would rather move it to a different name than `success`

Superseeded by #13
