### ISSUE TITLE
Enhancement: Log failure reason when resending an invite fails

### ISSUE THREAD

**Issue by robbieaverill** [Firesphere/silverstripe-stripeslack#9]
If for example a user already belongs to the Slack channel, the SlackInvite record will show that the invite was not successful. When resending the invite it fails again, and the record still says invite was not successful and still shows the re-send button.

It might be nice to store a "resend request message" or something so I could see from the admin area why a re-send request didn't succeed.

**Comment by Firesphere** [comment]
Would you expect _all_ messages in the admin, or just the last one?

p.s.
I've added the known "all is already good" type of errors to the exception of setting the Invited flag to true anyway.

**Comment by robbieaverill** [comment]
The use case was that I went to retry an invite for a user and it didn't say anything in the CMS but showed the same retry icon again. Turns out he was already in the channel. Would be good if it said failure reason was that the user was already invited or whatever.

**Comment by Firesphere** [comment]
Right, yeps, makes sense :) Especially errors that returned "I did not need to take any action" from Slack, except "already_invited" were not updating the user properly either way.

Like I said, the "already invited" and variations (There are 2 as far as I'm aware, already invited and already in team) on that are now used to set the user to `true` anyway in the updates branch, but adding the last message to the CMS would indeed be a good idea :)

**Comment by Firesphere** [comment]
I think this is related to the initial work I did to show a proper error message or success message in the CMS. They could hook in to the same response, saying "success, user already invited" etc. in the CMS. I'm unsure what is breaking that functionality that should be default though.

**Comment by robbieaverill** [comment]
Sounds good!

**Comment by Firesphere** [comment]
Failure reason now stored in a user-friendly bit of text taken from Slack.
